version: "3"
services:
  mysql-standalone:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=myfirstdb
    ports:
      - 3306:3306

  docker-springboot-batch:
    image: pavanbhagathi1234/javabatch:v1
    ports:
      - 8086:8086
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone