version: "3"


services:
  batchmysql-database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: myfirstdb
    ports:
      - 3036:3036

  java-batch:
    image: pavanbhagathi1234/javabatch:latest
    ports:
      - 8000:8000
    networks:
      - batch-network
    depends_on:
      - batch-batchmysql-database-1


networks:
  batch-network:


